---
name: run-help
'on': [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  help-linux:
    strategy:
      fail-fast: false
      matrix:
        config:
          - arch: 'x86_64'
            runner: 'ubuntu-latest'
            suffix: ''
          - arch: 'arm64'
            runner: 'ubuntu-24.04-arm'
            suffix: '-arm64'
    name: help-linux-${{ matrix.config.arch }}
    runs-on: ${{ matrix.config.runner }}
    steps:
      - name: Extract artifact
        uses: ./.github/actions/extract-artifact
        with:
          check-name: linux-${{ matrix.config.arch }}
          artifact-name: linux${{ matrix.config.suffix }}
      - name: Display help
        run: |
          cd squashfs-root/
          ./AppRun --help | grep "Usage: lmms"
  help-macos:
    strategy:
      fail-fast: false
      matrix:
        config:
          - arch: 'x86_64'
            runner: 'macos-latest'
          - arch: 'arm64'
            runner: 'macos-latest'
    name: help-macos-${{ matrix.config.arch }}
    runs-on: ${{ matrix.config.runner }}
    steps:
      - name: Extract artifact
        uses: ./.github/actions/extract-artifact
        with:
          check-name: macos-${{ matrix.config.arch }}
          artifact-name: macos-${{ matrix.config.arch }}
      - name: Display help
        run: |
          /tmp/LMMS.app/Contents/MacOS/lmms --help | grep "Usage: lmms"
